### ISSUE TITLE
Qué hacemos con la rama changing-directories?

### ISSUE THREAD

**Issue by maz-e** [AprendiendoAProgramar/GRT1979-Practice-Programming#2]
Cuando nos veamos te preguntare una duda que tengo sobre la rama que creé. Hay cosas que no entiendo¿?¿?

**Comment by GRT1979** [comment]
Si no quieres aprovechar nada de su contenido, cárgatela ;)

**Comment by GRT1979** [comment]
De hecho he estado haciendo alguna prueba:
1) He creado una nueva rama rama_prueba
2) Le he borrado los ficheros que tenía (al crearla te hace una copia de todo lo que había en la master)
3) Le he añadido un fichero .md de prueba
4) Y me he cargado mi rama local con: `git branch -D rama_prueba` (no la del repositorio remoto)
5) Ya no tendo en mi sistema de ficheros esa rama
6) He comprobado que como sigue existiendo en remoto, puedo cambiarme de rama y vuelven a aparecer los ficheros en mi sistema de ficheros
7) Ahora viene cuando voy a probar de borrar la rama del repositorio remoto con: `git push origin --delete rama_prueba`
8) Funcionó!! :)

**Comment by GRT1979** [comment]
Aquí puedes ver un histórico con la herramienta Git GUI [Imagen](https://drive.google.com/open?id=14BIYDofIlqHepEyDLNttQ-qrYCCNCqVu)

**Comment by maz-e** [comment]
Rama eliminada siguiendo tus indicaciones. Todo correcto!!!
